version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-sekolah
    restart: unless-stopped
    environment:
      POSTGRES_DB: project_sekolah
      POSTGRES_USER: sandy
      POSTGRES_PASSWORD: "${DB_PASSWORD:-015015}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandy -d project_sekolah"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Optimasi khusus 1 GB RAM VPS
    command: >
      postgres
        -c shared_buffers=128MB
        -c effective_cache_size=256MB
        -c work_mem=4MB
        -c maintenance_work_mem=64MB
        -c max_connections=30

volumes:
  postgres-data:
